### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-curate#11]
### Description

Curation blocks in this plugin should be able to opt-in to deduplication, where any posts displayed in any instances of other curation blocks (either manually selected, backfilled, or a combination of the two, see #8 #9 and #10) earlier on the page are excluded from display if the option is toggled on.

Caveat: this feature should only apply to automatic/backfilled posts and not curated posts. If an editor chooses a specific post to appear in a specific place and it has already appeared earlier on the page, deduplication should not override the editor's preference.

### Use Case

When a user adds multiple curated blocks to a page, they should be able to prevent the same post from appearing more than once on the entire page (across blocks). They should also have the ability to specify that a block should not deduplicate (e.g., show all posts matching a particular taxonomy term, even if they were displayed earlier on the page).

**Comment by mogmarsh** [comment]
I think it may be better to set deduplication at the entire page level, and then allow a block to **opt-out** if it is enabled.

**Comment by mogmarsh** [comment]
also, I think we should have a filterable setting to where a pinned post anywhere on the page will not be shown earlier on the page by backfill, so that a post only shows up once. Several clients have asked for this model.
