### ISSUE TITLE
Block Display Configuration Options

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-curate#12]
### Description

Curation blocks should have configurable options, including:

- An optional title to appear above the post list (default to empty/not displayed)
- The heading level for the title (default to h2)
- Whether to display featured images (options should be all, none, and first only)
- Whether to display an excerpt
- Whether to display the publish date
- Whether to display the author (need to support standard WP authors + CAP + Byline Manager, attempt to autodetect)
- Whether to display an eyebrow with the category (maybe make this flexible to pick the taxonomy)

### Use Case

When a user adds a curated content block, they should be able to specify how it should display so it can be used in different ways to create flexible layouts.

**Comment by mogmarsh** [comment]
Here are our current thoughts on how to implement some of these. We can be swayed to handle them differently.
✅ = done
💡 = discuss?
🔴 = not supported yet
🟡  = supported with caveats

- An optional title to appear above the post list (default to empty/not displayed)
✅ 💡 Just add a heading block - we're open to a custom heading block, if necessary.
- The heading level for the title (default to h2)
✅ Fully controllable in the heading block
- Whether to display featured images (options should be all, none, and first only)
✅ "All" and "none" is already supported with the post template. 🔴 We need to create the conditional plugin or figure out another way to handle "first only".
- Whether to display an excerpt
✅ Supported by post template.
- Whether to display the publish date
✅ Supported by post template
- Whether to display the author (need to support standard WP authors + CAP + Byline Manager, attempt to autodetect)
✅ Supported by post template. 🟡 _We probably need to make sure those other plugins play well with the core author block or have their own blocks_.
- Whether to display an eyebrow with the category (maybe make this flexible to pick the taxonomy)
✅ 🟡 Supported by the post template, _however an eyebrow block would need to be created in the project currently_. 💡 We could add an eyebrow block to the plugin, but there are many different ways of determining the eyebrow, so it would probably just be a default that gets filtered anyway.

**Comment by mogmarsh** [comment]
@kevinfodness any thoughts/questions on the above?

**Comment by kevinfodness** [comment]
That's fine for first only - in practice these will likely end up being different curation sections (e.g., hero vs. sidebar, built using core columns blocks). There's also the ability to use your own custom renderer and have this plugin handle the post lookup, then use something site-specific, which opens up a lot of possibilities for how things could be customized on a per-site basis without needing to write a lot of code. Agree with the general feedback that we want to avoid going too far down the road of assuming where this data will come from (e.g., eyebrow). I'm good with this as-is and will close.
