### ISSUE TITLE
Deleting a Pinned Post causes the block to crash when "Select Posts" is expanded

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-curate#120]
### Description of the bug

If a post is pinned, then deleted, the block will crash when the Select Posts panel of the sidebar is expanded.

### Steps To Reproduce

Pin a post in a query block
Save the page/post with the query block
Delete the post you pinned
Edit the page/post with the query block
Click on the query block, then click to expand "Select Posts"

**Comment by mogmarsh** [comment]
I think this may be fixed by https://github.com/alleyinteractive/alley-scripts/issues/543

**Comment by jacobschweitzer** [comment]
This is resolved, I followed the steps and then I saw this message in the "Select Posts" part of the Query block sidebar:
![Screenshot 2024-10-31 at 4 45 55 PM](https://github.com/user-attachments/assets/e68916b4-3beb-43fb-acf9-4984ac3bf145)
