### ISSUE TITLE
Make Output Filterable

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-curate#13]
### Description

There should be a default template that works out of the box, but output for blocks should be filterable. The filter should provide the list of posts to display in the block (which initially would just contain the post ID, but could be extended later to include overrides for curated posts where titles/descriptions/images/etc may need to be customized) and if the filter returns a value, output it and bail out on the normal block render routine. This will allow the query/deduping/etc functionality of this plugin to execute before the filter, but allow the output to be fully customized by a user if desired.

Example data structure to be passed to the filter:

```php
$post_list = [
  [
    'ID' => 1234,
  ],
  [
    'ID' => 2345,
  ],
];
```

This allows us to add additional properties to the arrays later for overrides of title/excerpt/featured image/etc without having to refactor existing code that uses an earlier version of the plugin.

### Use Case

When a developer incorporates this plugin into their site, they should be able to use all of its functionality for curation, backfill, deduplication, performant queries, etc, but opt out of its default templating in favor of templating defined by the developer.

**Comment by mogmarsh** [comment]
the [`render_block`](https://developer.wordpress.org/reference/hooks/render_block/) filter may be able to handle this... we'll have to see what data is available in the `$block` parameter

**Comment by kevinfodness** [comment]
Not going to do this - using the Post Template block in the editor, want to make editor have parity with the frontend, and if it is required to filter block output, that can be done using render_block like we would do for anything else. Nothing special needs to be done here.
