### ISSUE TITLE
Fatal on front end when trending is set as source but parsely not setup

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-curate#159]
### Description of the bug

Viewing a Query block that has trending set for the source results in an error on the front end if parsely is not set up.

### Steps To Reproduce

set up a Query block and in the code view set orderby to trending

	<div class="wp-block-wp-curate-query">
	
	<div class="wp-block-wp-curate-post">
	<div class="wp-block-columns is-not-stacked-on-mobile">
	<div class="wp-block-column" style="flex-basis:60%">

	
	<div class="wp-block-group">

	</div>
	</div>
	

	
	<div class="wp-block-column" style="flex-basis:40%"></div>
	</div>
	</div>
	
	</div>
	

make sure parsely is not configured.
view it on the front end.

**Comment by kevinfodness** [comment]
This was fixed by #160
