### ISSUE TITLE
Change order and label(s) of sidebar settings

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-curate#50]
### Description

Changing the pinned posts will probably happen more often than changing the backfill settings, so the pinned posts should be moved to the top. The section currently labeled "Block Settings" should be more descriptive, like "backfill settings".

**Comment by dlh01** [comment]
In this branch, I've moved the pinned post setting to the top, and I renamed "Block Settings" to "Filters": https://github.com/alleyinteractive/wp-curate/compare/feature/control-labels?expand=1

After I did those two things, it occurred to me that the control for the number of posts is not only not a filter, it affects the number of pinned posts that are available. So perhaps that control and the offset control should themselves go above pinned posts in a new section. For example:

<img width="337" alt="Screenshot 2023-09-14 at 1 11 11 AM" src="https://github.com/alleyinteractive/wp-curate/assets/697432/e9e91ac8-c0aa-418b-963f-30f29244805e">

As a bonus, the remaining controls under "Filters" would actually be filters.
