### ISSUE TITLE
Only show deduplication slot fill if more than one query block is present

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-curate#52]
# User Story

> As an editor, I don't want to see the Deduplication slotfill unless I have added at least to WP Curate Query blocks to a page.

# Acceptance Criteria

- Ensure that the Deduplication slotfill does not appear unless at least two WP Curate Query blocks are present on a page.
- Ensure that this still works as expected even if a Query block is inside of another block (e.g., a column).

# Technical Details

- You should be able to get a list of all blocks on the page from the editor's data, which should update as changes are made. This can be looped over (perhaps recursively?) to find instances of the query block.

**Comment by renatonascalves** [comment]
Add an option to override this via code. In case it might be necessary. We have one client that needs it even when there is only one query block present.

**Comment by kevinfodness** [comment]
@renatonascalves deduplication only applies to multiple blocks. Individual blocks are already deduplicated. The setting applies to when multiple blocks return query results and block 2 shouldn't contain results from block 1, for example.

**Comment by renatonascalves** [comment]
@kevinfodness Disregard my comment.

We have a client that needed that slotfill to be available even if only one block was available in the post. The slotfill would be connected with other queries in the homepage post/page and communicate the need to dedupe the block posts from the rest of the page queries. But that _need_ changed.

Please, feel free to disregard my comment/feedback.
