### ISSUE TITLE
`wp_curate_deduplication` meta is only registered for posts

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-curate#56]
### Description of the bug

The `wp_curate_deduplication` meta is only registered for posts, so it can't be enabled for any other post types (like pages).
https://github.com/alleyinteractive/wp-curate/blob/develop/config/post-meta.json#L3-L5

### Steps To Reproduce

1. Edit a page
2. Enable deduplication in the slot fill
3. Save
4. The toggle reverts back to unselected.

### Additional Information

We should either register it for all post types or move away from the json config file and register it manually using a filterable list of post types (which could be shared with https://github.com/alleyinteractive/wp-curate/issues/56)

**Comment by renatonascalves** [comment]
@mogmarsh Is this issue still relevant?

The meta key is already registered by all post types, see here: https://github.com/alleyinteractive/wp-curate/blob/63587438c7bceba2feeab3bcd69abeb3f2296d9d/config/post-meta.json#L4

And I confirmed in a client project that it is saving properly in posts/pages...

**Comment by mogmarsh** [comment]
@renatonascalves iI put in a quick fix to register it for all. https://github.com/alleyinteractive/wp-curate/pull/72 Will implement a better fix to register it only where necessary.

**Comment by mogmarsh** [comment]
fixed in https://github.com/alleyinteractive/wp-curate/pull/72
