### ISSUE TITLE
Curation removes some attributes `postTypes` but not others `categories`

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/wp-curate#78]
### Description

Curating a post removes the `postTypes` attributes but not the `categories` attribute.

### Use Case

Block curating a post.

**Comment by mogmarsh** [comment]
@renatonascalves where are these attributes removed or not removed from?

**Comment by renatonascalves** [comment]
@mogmarsh 

The attributes inside the block. The example below is the block with one post curated and with one category set.
```
<!-- wp:wp-curate/query {"maxNumberOfPosts":4,"minNumberOfPosts":4,"numberOfPosts":4,"posts":[180842,null,null,null],"terms":{"category":[{"id":5944,"title":"News","url":"https://site/news/","type":"category"}]}} -->
```

While testing, I found that by default: the `postTypes` query parameter is set, but any block change removes it, even though it looks like it is set in the editor. The same doesn't happen for the terms, where you get an empty array if you remove it later.

```
<!-- wp:wp-curate/query {"maxNumberOfPosts":4,"minNumberOfPosts":4,"numberOfPosts":4,"postTypes":["post"]} -->
```

<img width="385" alt="Screenshot 2023-10-16 at 21 26 19" src="https://github.com/alleyinteractive/wp-curate/assets/19148962/0ca90992-f176-4329-8de6-964f679cdbcd">

**Comment by renatonascalves** [comment]
With #82, this is not longer relevant. But a quick note to the future: I'd expect the Query Parameters present in the sidebar to be reflected in the block attributes, but it currently does not work that way.
