### ISSUE TITLE
There is no visual indication for the `minNumberOfPosts` in the editor

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/wp-curate#79]
### Description

If I set a block to use this rule: `minNumberOfPosts: 4`, there is no visual indication in the block editor about that. An editor can curate only one post and disregard this "rule".

### Use Case

As titled.

**Comment by mogmarsh** [comment]
this should determine the minimum for the number of posts slider in the sidebar (I believe the maxNumberOfPosts is required too). It is not for validation, but for letting the template designer say that the end user can choose to show between 3 and 5 posts for instance. Then whatever posts are not curated will be backfilled.

**Comment by renatonascalves** [comment]
Tks! After playing more with the interface, I noticed this was a misunderstanding on my part.
